name: "Training Workflow"
start_node: "planner_node"

nodes:
  - id: "planner_node"
    agent: "planner"
    inputs:
      user_request: "Train a ResNet50 model on CIFAR-10"
    next:
      - "trainer_node"

  - id: "trainer_node"
    agent: "trainer"
    inputs:
      model_config: "resnet50.yaml"
      dataset_path: "s3://bucket/cifar10"
      epochs: 10
