name: "Smart Routing Workflow"
version: "1.0"
description: "Workflow that routes user requests to Greeting, DataProcessing, or ExtraTopic agents using an LLM Planner."

config:
  service_name: "Avaloka AI"
  service_info: "We help you clean and process your data with ease."
  llm_config:
    provider: "groq"
    model: "llama-3.3-70b-versatile"

nodes:
  start_node:
    type: "agent"
    agent_id: "planner"

  router_node:
    type: "router"
    condition: "$start_node.next_action"

  greeting_node:
    type: "agent"
    agent_id: "greeting"

  data_processing_node:
    type: "agent"
    agent_id: "data_processor"

  extra_topic_node:
    type: "agent"
    agent_id: "extra_topic"
    config:
      service_info: "We handle big data so you don't have to!"

  end_node:
    type: "end"

edges:
  - from: start_node
    to: router_node

  - from: router_node
    to: greeting_node
    condition: "greeting"

  - from: router_node
    to: data_processing_node
    condition: "data_processor"

  - from: router_node
    to: extra_topic_node
    condition: "extra_topic"

  - from: router_node
    to: extra_topic_node
    default: true

  - from: greeting_node
    to: end_node

  - from: data_processing_node
    to: end_node

  - from: extra_topic_node
    to: end_node

start_node: "start_node"
